export const EMOJI_CATEGORIES = {
  faces: [
    { emoji: '😀', name: 'grinning face' },
    { emoji: '😃', name: 'grinning face with big eyes' },
    { emoji: '😄', name: 'grinning face with smiling eyes' },
    { emoji: '😁', name: 'beaming face with smiling eyes' },
    { emoji: '😆', name: 'grinning squinting face' },
    { emoji: '😅', name: 'grinning face with sweat' },
    { emoji: '😂', name: 'face with tears of joy' },
    { emoji: '🤣', name: 'rolling on the floor laughing' },
    { emoji: '😊', name: 'smiling face with smiling eyes' },
    { emoji: '😇', name: 'smiling face with halo' },
    { emoji: '🙂', name: 'slightly smiling face' },
    { emoji: '🙃', name: 'upside-down face' },
    { emoji: '😉', name: 'winking face' },
    { emoji: '😌', name: 'relieved face' },
    { emoji: '😍', name: 'smiling face with heart-eyes' },
    { emoji: '🥰', name: 'smiling face with hearts' },
    { emoji: '😘', name: 'face blowing a kiss' },
    { emoji: '😗', name: 'kissing face' },
    { emoji: '😙', name: 'kissing face with smiling eyes' },
    { emoji: '😚', name: 'kissing face with closed eyes' },
    { emoji: '😋', name: 'face savoring food' },
    { emoji: '😛', name: 'face with tongue' },
    { emoji: '😝', name: 'squinting face with tongue' },
    { emoji: '😜', name: 'winking face with tongue' },
    { emoji: '🤪', name: 'zany face' },
    { emoji: '🤨', name: 'face with raised eyebrow' },
    { emoji: '🧐', name: 'face with monocle' },
    { emoji: '🤓', name: 'nerd face' },
    { emoji: '😎', name: 'smiling face with sunglasses' },
    { emoji: '🤩', name: 'star-struck' },
    { emoji: '🥳', name: 'partying face' }
  ],
  hands: [
    { emoji: '👋', name: 'waving hand' },
    { emoji: '🤚', name: 'raised back of hand' },
    { emoji: '🖐️', name: 'hand with fingers splayed' },
    { emoji: '✋', name: 'raised hand' },
    { emoji: '🖖', name: 'vulcan salute' },
    { emoji: '👌', name: 'OK hand' },
    { emoji: '🤌', name: 'pinched fingers' },
    { emoji: '🤏', name: 'pinching hand' },
    { emoji: '✌️', name: 'victory hand' },
    { emoji: '🤞', name: 'crossed fingers' },
    { emoji: '🤟', name: 'love-you gesture' },
    { emoji: '🤘', name: 'sign of the horns' },
    { emoji: '🤙', name: 'call me hand' },
    { emoji: '👈', name: 'backhand index pointing left' },
    { emoji: '👉', name: 'backhand index pointing right' },
    { emoji: '👆', name: 'backhand index pointing up' },
    { emoji: '🖕', name: 'middle finger' },
    { emoji: '👇', name: 'backhand index pointing down' },
    { emoji: '☝️', name: 'index pointing up' },
    { emoji: '👍', name: 'thumbs up' },
    { emoji: '👎', name: 'thumbs down' },
    { emoji: '👊', name: 'oncoming fist' },
    { emoji: '✊', name: 'raised fist' },
    { emoji: '🤛', name: 'left-facing fist' },
    { emoji: '🤜', name: 'right-facing fist' },
    { emoji: '👏', name: 'clapping hands' },
    { emoji: '🙌', name: 'raising hands' },
    { emoji: '👐', name: 'open hands' },
    { emoji: '🤲', name: 'palms up together' },
    { emoji: '🤝', name: 'handshake' },
    { emoji: '🙏', name: 'folded hands' }
  ],
  hearts: [
    { emoji: '❤️', name: 'red heart' },
    { emoji: '🧡', name: 'orange heart' },
    { emoji: '💛', name: 'yellow heart' },
    { emoji: '💚', name: 'green heart' },
    { emoji: '💙', name: 'blue heart' },
    { emoji: '💜', name: 'purple heart' },
    { emoji: '🖤', name: 'black heart' },
    { emoji: '🤍', name: 'white heart' },
    { emoji: '🤎', name: 'brown heart' },
    { emoji: '💔', name: 'broken heart' },
    { emoji: '❣️', name: 'heart exclamation' },
    { emoji: '💕', name: 'two hearts' },
    { emoji: '💞', name: 'revolving hearts' },
    { emoji: '💓', name: 'beating heart' },
    { emoji: '💗', name: 'growing heart' },
    { emoji: '💖', name: 'sparkling heart' },
    { emoji: '💘', name: 'heart with arrow' },
    { emoji: '💝', name: 'heart with ribbon' },
    { emoji: '💟', name: 'heart decoration' },
    { emoji: '♥️', name: 'heart suit' },
    { emoji: '💌', name: 'love letter' },
    { emoji: '💋', name: 'kiss mark' },
    { emoji: '💍', name: 'ring' },
    { emoji: '💎', name: 'gem stone' }
  ],
  objects: [
    { emoji: '⚽', name: 'soccer ball' },
    { emoji: '🏀', name: 'basketball' },
    { emoji: '🏈', name: 'american football' },
    { emoji: '⚾', name: 'baseball' },
    { emoji: '🥎', name: 'softball' },
    { emoji: '🎾', name: 'tennis' },
    { emoji: '🏐', name: 'volleyball' },
    { emoji: '🏉', name: 'rugby football' },
    { emoji: '🥏', name: 'flying disc' },
    { emoji: '🎱', name: 'pool 8 ball' },
    { emoji: '🪀', name: 'yo-yo' },
    { emoji: '🏓', name: 'ping pong' },
    { emoji: '🏸', name: 'badminton' },
    { emoji: '🏒', name: 'ice hockey' },
    { emoji: '🏑', name: 'field hockey' },
    { emoji: '🥍', name: 'lacrosse' },
    { emoji: '🏏', name: 'cricket game' },
    { emoji: '🪃', name: 'boomerang' },
    { emoji: '🥅', name: 'goal net' },
    { emoji: '⛳', name: 'flag in hole' },
    { emoji: '🪁', name: 'kite' },
    { emoji: '🏹', name: 'bow and arrow' },
    { emoji: '🎣', name: 'fishing pole' },
    { emoji: '🤿', name: 'diving mask' },
    { emoji: '🥊', name: 'boxing glove' },
    { emoji: '🥋', name: 'martial arts uniform' }
  ],
  animals: [
    { emoji: '🐶', name: 'dog face' },
    { emoji: '🐱', name: 'cat face' },
    { emoji: '🐭', name: 'mouse face' },
    { emoji: '🐹', name: 'hamster' },
    { emoji: '🐰', name: 'rabbit face' },
    { emoji: '🦊', name: 'fox' },
    { emoji: '🐻', name: 'bear' },
    { emoji: '🐼', name: 'panda' },
    { emoji: '🐨', name: 'koala' },
    { emoji: '🐯', name: 'tiger face' },
    { emoji: '🦁', name: 'lion' },
    { emoji: '🐮', name: 'cow face' },
    { emoji: '🐷', name: 'pig face' },
    { emoji: '🐸', name: 'frog' },
    { emoji: '🐵', name: 'monkey face' },
    { emoji: '🐔', name: 'chicken' },
    { emoji: '🐧', name: 'penguin' },
    { emoji: '🐦', name: 'bird' },
    { emoji: '🐤', name: 'baby chick' },
    { emoji: '🦆', name: 'duck' },
    { emoji: '🦅', name: 'eagle' },
    { emoji: '🦉', name: 'owl' },
    { emoji: '🦇', name: 'bat' },
    { emoji: '🐺', name: 'wolf' },
    { emoji: '🐗', name: 'boar' }
  ],
  food: [
    { emoji: '🍏', name: 'green apple' },
    { emoji: '🍎', name: 'red apple' },
    { emoji: '🍐', name: 'pear' },
    { emoji: '🍊', name: 'tangerine' },
    { emoji: '🍋', name: 'lemon' },
    { emoji: '🍌', name: 'banana' },
    { emoji: '🍉', name: 'watermelon' },
    { emoji: '🍇', name: 'grapes' },
    { emoji: '🍓', name: 'strawberry' },
    { emoji: '🫐', name: 'blueberries' },
    { emoji: '🍈', name: 'melon' },
    { emoji: '🍒', name: 'cherries' },
    { emoji: '🍑', name: 'peach' },
    { emoji: '🥭', name: 'mango' },
    { emoji: '🍍', name: 'pineapple' },
    { emoji: '🥥', name: 'coconut' },
    { emoji: '🥝', name: 'kiwi fruit' },
    { emoji: '🍅', name: 'tomato' },
    { emoji: '🍆', name: 'eggplant' },
    { emoji: '🥑', name: 'avocado' },
    { emoji: '🥦', name: 'broccoli' },
    { emoji: '🥬', name: 'leafy green' },
    { emoji: '🥒', name: 'cucumber' },
    { emoji: '🌶️', name: 'hot pepper' },
    { emoji: '🫑', name: 'bell pepper' }
  ],
  weather: [
    { emoji: '☀️', name: 'sun' },
    { emoji: '🌤️', name: 'sun behind small cloud' },
    { emoji: '⛅', name: 'sun behind cloud' },
    { emoji: '🌥️', name: 'sun behind large cloud' },
    { emoji: '☁️', name: 'cloud' },
    { emoji: '🌦️', name: 'sun behind rain cloud' },
    { emoji: '🌧️', name: 'cloud with rain' },
    { emoji: '⛈️', name: 'cloud with lightning and rain' },
    { emoji: '🌩️', name: 'cloud with lightning' },
    { emoji: '⚡', name: 'lightning' },
    { emoji: '❄️', name: 'snowflake' },
    { emoji: '☃️', name: 'snowman' },
    { emoji: '⛄', name: 'snowman without snow' },
    { emoji: '🌪️', name: 'tornado' },
    { emoji: '🌫️', name: 'fog' },
    { emoji: '🌊', name: 'water wave' },
    { emoji: '💧', name: 'droplet' },
    { emoji: '💦', name: 'sweat droplets' },
    { emoji: '☔', name: 'umbrella with rain drops' },
    { emoji: '☂️', name: 'umbrella' },
    { emoji: '🌈', name: 'rainbow' },
    { emoji: '🌪️', name: 'tornado' },
    { emoji: '🌀', name: 'cyclone' },
    { emoji: '🌁', name: 'foggy' },
    { emoji: '🌡️', name: 'thermometer' }
  ],
  vehicles: [
    { emoji: '🚗', name: 'automobile' },
    { emoji: '🚕', name: 'taxi' },
    { emoji: '🚙', name: 'sport utility vehicle' },
    { emoji: '🚌', name: 'bus' },
    { emoji: '🚎', name: 'trolleybus' },
    { emoji: '🏎️', name: 'racing car' },
    { emoji: '🚓', name: 'police car' },
    { emoji: '🚑', name: 'ambulance' },
    { emoji: '🚒', name: 'fire engine' },
    { emoji: '🚐', name: 'minibus' },
    { emoji: '🛻', name: 'pickup truck' },
    { emoji: '🚚', name: 'delivery truck' },
    { emoji: '🚛', name: 'articulated lorry' },
    { emoji: '🚜', name: 'tractor' },
    { emoji: '🦽', name: 'manual wheelchair' },
    { emoji: '🦼', name: 'motorized wheelchair' },
    { emoji: '🛴', name: 'kick scooter' },
    { emoji: '🚲', name: 'bicycle' },
    { emoji: '🛵', name: 'motor scooter' },
    { emoji: '🏍️', name: 'motorcycle' },
    { emoji: '🛺', name: 'auto rickshaw' },
    { emoji: '🚔', name: 'oncoming police car' },
    { emoji: '✈️', name: 'airplane' },
    { emoji: '🛩️', name: 'small airplane' },
    { emoji: '🚀', name: 'rocket' }
  ],
  symbols: [
    { emoji: '🔴', name: 'red circle' },
    { emoji: '🟠', name: 'orange circle' },
    { emoji: '🟡', name: 'yellow circle' },
    { emoji: '🟢', name: 'green circle' },
    { emoji: '🔵', name: 'blue circle' },
    { emoji: '🟣', name: 'purple circle' },
    { emoji: '🟤', name: 'brown circle' },
    { emoji: '⚫', name: 'black circle' },
    { emoji: '⚪', name: 'white circle' },
    { emoji: '🟥', name: 'red square' },
    { emoji: '🟧', name: 'orange square' },
    { emoji: '🟨', name: 'yellow square' },
    { emoji: '🟩', name: 'green square' },
    { emoji: '🟦', name: 'blue square' },
    { emoji: '🟪', name: 'purple square' },
    { emoji: '🟫', name: 'brown square' },
    { emoji: '⬛', name: 'black large square' },
    { emoji: '⬜', name: 'white large square' },
    { emoji: '🔶', name: 'large orange diamond' },
    { emoji: '🔷', name: 'large blue diamond' },
    { emoji: '🔸', name: 'small orange diamond' },
    { emoji: '🔹', name: 'small blue diamond' },
    { emoji: '🔺', name: 'red triangle pointed up' },
    { emoji: '🔻', name: 'red triangle pointed down' },
    { emoji: '💠', name: 'diamond with a dot' }
  ],
  holidays: [
    { emoji: '🎄', name: 'Christmas tree' },
    { emoji: '🎅', name: 'Santa Claus' },
    { emoji: '🤶', name: 'Mrs. Claus' },
    { emoji: '🧑‍🎄', name: 'mx claus' },
    { emoji: '🎁', name: 'wrapped gift' },
    { emoji: '🕎', name: 'menorah' },
    { emoji: '🪔', name: 'diya lamp' },
    { emoji: '🎃', name: 'jack-o-lantern' },
    { emoji: '👻', name: 'ghost' },
    { emoji: '💀', name: 'skull' },
    { emoji: '🕷️', name: 'spider' },
    { emoji: '🕸️', name: 'spider web' },
    { emoji: '🎆', name: 'fireworks' },
    { emoji: '🎇', name: 'sparkler' },
    { emoji: '🧨', name: 'firecracker' },
    { emoji: '✨', name: 'sparkles' },
    { emoji: '🎈', name: 'balloon' },
    { emoji: '🎉', name: 'party popper' },
    { emoji: '🎊', name: 'confetti ball' },
    { emoji: '🎎', name: 'Japanese dolls' },
    { emoji: '🎏', name: 'carp streamer' },
    { emoji: '🎐', name: 'wind chime' },
    { emoji: '🎀', name: 'ribbon' },
    { emoji: '🎗️', name: 'reminder ribbon' },
    { emoji: '🪅', name: 'piñata' }
  ],
  flags: [
    { emoji: '🏳️', name: 'white flag' },
    { emoji: '🏴', name: 'black flag' },
    { emoji: '🏴‍☠️', name: 'pirate flag' },
    { emoji: '🏁', name: 'chequered flag' },
    { emoji: '🚩', name: 'triangular flag' },
    { emoji: '🏳️‍🌈', name: 'rainbow flag' },
    { emoji: '🏳️‍⚧️', name: 'transgender flag' },
    { emoji: '🇺🇳', name: 'United Nations' },
    { emoji: '🇦🇫', name: 'Afghanistan' },
    { emoji: '🇦🇽', name: 'Åland Islands' },
    { emoji: '🇦🇱', name: 'Albania' },
    { emoji: '🇩🇿', name: 'Algeria' },
    { emoji: '🇦🇸', name: 'American Samoa' },
    { emoji: '🇦🇩', name: 'Andorra' },
    { emoji: '🇦🇴', name: 'Angola' },
    { emoji: '🇦🇮', name: 'Anguilla' },
    { emoji: '🇦🇶', name: 'Antarctica' },
    { emoji: '🇦🇬', name: 'Antigua & Barbuda' },
    { emoji: '🇦🇷', name: 'Argentina' },
    { emoji: '🇦🇲', name: 'Armenia' },
    { emoji: '🇦🇼', name: 'Aruba' },
    { emoji: '🇦🇺', name: 'Australia' },
    { emoji: '🇦🇹', name: 'Austria' },
    { emoji: '🇦🇿', name: 'Azerbaijan' },
    { emoji: '🇧🇸', name: 'Bahamas' }
  ],
  plants: [
    { emoji: '🌵', name: 'cactus' },
    { emoji: '🎄', name: 'Christmas tree' },
    { emoji: '🌲', name: 'evergreen tree' },
    { emoji: '🌳', name: 'deciduous tree' },
    { emoji: '🌴', name: 'palm tree' },
    { emoji: '🪵', name: 'wood' },
    { emoji: '🌱', name: 'seedling' },
    { emoji: '🌿', name: 'herb' },
    { emoji: '☘️', name: 'shamrock' },
    { emoji: '🍀', name: 'four leaf clover' },
    { emoji: '🎍', name: 'pine decoration' },
    { emoji: '🪴', name: 'potted plant' },
    { emoji: '🎋', name: 'tanabata tree' },
    { emoji: '🍃', name: 'leaf fluttering in wind' },
    { emoji: '🍂', name: 'fallen leaf' },
    { emoji: '🍁', name: 'maple leaf' },
    { emoji: '🍄', name: 'mushroom' },
    { emoji: '🐚', name: 'sea shell' },
    { emoji: '🪨', name: 'rock' },
    { emoji: '🌾', name: 'sheaf of rice' },
    { emoji: '💐', name: 'bouquet' },
    { emoji: '🌷', name: 'tulip' },
    { emoji: '🌹', name: 'rose' },
    { emoji: '🥀', name: 'wilted flower' },
    { emoji: '🌺', name: 'hibiscus' }
  ],
  clothing: [
    { emoji: '🧥', name: 'coat' },
    { emoji: '🥼', name: 'lab coat' },
    { emoji: '🦺', name: 'safety vest' },
    { emoji: '👚', name: 'womans clothes' },
    { emoji: '👕', name: 't-shirt' },
    { emoji: '👖', name: 'jeans' },
    { emoji: '🩲', name: 'briefs' },
    { emoji: '🩳', name: 'shorts' },
    { emoji: '👔', name: 'necktie' },
    { emoji: '👗', name: 'dress' },
    { emoji: '👙', name: 'bikini' },
    { emoji: '🩱', name: 'one-piece swimsuit' },
    { emoji: '👘', name: 'kimono' },
    { emoji: '🥻', name: 'sari' },
    { emoji: '🩴', name: 'thong sandal' },
    { emoji: '🧦', name: 'socks' },
    { emoji: '🧤', name: 'gloves' },
    { emoji: '🧣', name: 'scarf' },
    { emoji: '🎩', name: 'top hat' },
    { emoji: '🧢', name: 'billed cap' },
    { emoji: '👒', name: 'womans hat' },
    { emoji: '🎓', name: 'graduation cap' },
    { emoji: '⛑️', name: 'rescue workers helmet' },
    { emoji: '🪖', name: 'military helmet' },
    { emoji: '👑', name: 'crown' }
  ],
  time: [
    { emoji: '🕛', name: 'twelve oclock' },
    { emoji: '🕧', name: 'twelve-thirty' },
    { emoji: '🕐', name: 'one oclock' },
    { emoji: '🕜', name: 'one-thirty' },
    { emoji: '🕑', name: 'two oclock' },
    { emoji: '🕝', name: 'two-thirty' },
    { emoji: '🕒', name: 'three oclock' },
    { emoji: '🕞', name: 'three-thirty' },
    { emoji: '🕓', name: 'four oclock' },
    { emoji: '🕟', name: 'four-thirty' },
    { emoji: '🕔', name: 'five oclock' },
    { emoji: '🕠', name: 'five-thirty' },
    { emoji: '🕕', name: 'six oclock' },
    { emoji: '🕡', name: 'six-thirty' },
    { emoji: '🕖', name: 'seven oclock' },
    { emoji: '🕢', name: 'seven-thirty' },
    { emoji: '🕗', name: 'eight oclock' },
    { emoji: '🕣', name: 'eight-thirty' },
    { emoji: '🕘', name: 'nine oclock' },
    { emoji: '🕤', name: 'nine-thirty' },
    { emoji: '🕙', name: 'ten oclock' },
    { emoji: '🕥', name: 'ten-thirty' },
    { emoji: '🕚', name: 'eleven oclock' },
    { emoji: '🕦', name: 'eleven-thirty' },
    { emoji: '⏰', name: 'alarm clock' }
  ],
  zodiac: [
    { emoji: '♈', name: 'Aries' },
    { emoji: '♉', name: 'Taurus' },
    { emoji: '♊', name: 'Gemini' },
    { emoji: '♋', name: 'Cancer' },
    { emoji: '♌', name: 'Leo' },
    { emoji: '♍', name: 'Virgo' },
    { emoji: '♎', name: 'Libra' },
    { emoji: '♏', name: 'Scorpio' },
    { emoji: '♐', name: 'Sagittarius' },
    { emoji: '♑', name: 'Capricorn' },
    { emoji: '♒', name: 'Aquarius' },
    { emoji: '♓', name: 'Pisces' },
    { emoji: '⛎', name: 'Ophiuchus' },
    { emoji: '🔯', name: 'dotted six-pointed star' },
    { emoji: '🔮', name: 'crystal ball' },
    { emoji: '🪄', name: 'magic wand' },
    { emoji: '🧿', name: 'nazar amulet' },
    { emoji: '📿', name: 'prayer beads' },
    { emoji: '💎', name: 'gem stone' },
    { emoji: '🔱', name: 'trident emblem' },
    { emoji: '⚜️', name: 'fleur-de-lis' },
    { emoji: '🕎', name: 'menorah' },
    { emoji: '☸️', name: 'wheel of dharma' },
    { emoji: '☯️', name: 'yin yang' },
    { emoji: '☮️', name: 'peace symbol' }
  ],
  office: [
    { emoji: '📁', name: 'file folder' },
    { emoji: '📂', name: 'open file folder' },
    { emoji: '🗂️', name: 'card index dividers' },
    { emoji: '📅', name: 'calendar' },
    { emoji: '📆', name: 'tear-off calendar' },
    { emoji: '🗒️', name: 'spiral notepad' },
    { emoji: '🗓️', name: 'spiral calendar' },
    { emoji: '📇', name: 'card index' },
    { emoji: '📈', name: 'chart increasing' },
    { emoji: '📉', name: 'chart decreasing' },
    { emoji: '📊', name: 'bar chart' },
    { emoji: '📋', name: 'clipboard' },
    { emoji: '📌', name: 'pushpin' },
    { emoji: '📍', name: 'round pushpin' },
    { emoji: '📎', name: 'paperclip' },
    { emoji: '🖇️', name: 'linked paperclips' },
    { emoji: '📏', name: 'straight ruler' },
    { emoji: '📐', name: 'triangular ruler' },
    { emoji: '✂️', name: 'scissors' },
    { emoji: '🗃️', name: 'card file box' },
    { emoji: '🗄️', name: 'file cabinet' },
    { emoji: '🗑️', name: 'wastebasket' },
    { emoji: '🔒', name: 'locked' },
    { emoji: '🔓', name: 'unlocked' },
    { emoji: '📝', name: 'memo' }
  ],
  music: [
    { emoji: '🎵', name: 'musical note' },
    { emoji: '🎶', name: 'musical notes' },
    { emoji: '🎼', name: 'musical score' },
    { emoji: '🎤', name: 'microphone' },
    { emoji: '🎧', name: 'headphone' },
    { emoji: '📻', name: 'radio' },
    { emoji: '🎷', name: 'saxophone' },
    { emoji: '🎸', name: 'guitar' },
    { emoji: '🎹', name: 'musical keyboard' },
    { emoji: '🎺', name: 'trumpet' },
    { emoji: '🎻', name: 'violin' },
    { emoji: '🪕', name: 'banjo' },
    { emoji: '🥁', name: 'drum' },
    { emoji: '🪘', name: 'long drum' },
    { emoji: '📯', name: 'postal horn' },
    { emoji: '🔔', name: 'bell' },
    { emoji: '🎚️', name: 'level slider' },
    { emoji: '🎛️', name: 'control knobs' },
    { emoji: '🎙️', name: 'studio microphone' },
    { emoji: '🎚️', name: 'level slider' },
    { emoji: '🎛️', name: 'control knobs' },
    { emoji: '🎤', name: 'microphone' },
    { emoji: '🎧', name: 'headphone' },
    { emoji: '📢', name: 'loudspeaker' },
    { emoji: '📣', name: 'megaphone' }
  ],
  household: [
    { emoji: '🚪', name: 'door' },
    { emoji: '🪑', name: 'chair' },
    { emoji: '🛏️', name: 'bed' },
    { emoji: '🛋️', name: 'couch and lamp' },
    { emoji: '🪟', name: 'window' },
    { emoji: '🪞', name: 'mirror' },
    { emoji: '🛁', name: 'bathtub' },
    { emoji: '🚿', name: 'shower' },
    { emoji: '🛀', name: 'person taking bath' },
    { emoji: '🪠', name: 'plunger' },
    { emoji: '🧻', name: 'roll of paper' },
    { emoji: '🧸', name: 'teddy bear' },
    { emoji: '🧷', name: 'safety pin' },
    { emoji: '🧹', name: 'broom' },
    { emoji: '🧺', name: 'basket' },
    { emoji: '🧻', name: 'roll of paper' },
    { emoji: '🧼', name: 'soap' },
    { emoji: '🧽', name: 'sponge' },
    { emoji: '🧯', name: 'fire extinguisher' },
    { emoji: '🛒', name: 'shopping cart' },
    { emoji: '🛍️', name: 'shopping bags' },
    { emoji: '🪣', name: 'bucket' },
    { emoji: '🪥', name: 'toothbrush' },
    { emoji: '🧴', name: 'lotion bottle' },
    { emoji: '🪒', name: 'razor' }
  ]
};